//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCasoEstudio2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CasoEstudioMNEntities1 : DbContext
    {
        public CasoEstudioMNEntities1()
            : base("name=CasoEstudioMNEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CasasSistema> CasasSistema { get; set; }
    
        public virtual ObjectResult<ObtenerCasas_Result> ObtenerCasas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerCasas_Result>("ObtenerCasas");
        }
    }
}
